image: node:alpine3.14

before_script:
  - apk add chromium
  - npm install

build:
  stage: build
  script:
    - npm install gulp gulp-concat gulp-header-comment gulp-rename gulp-terser gulp-umd
    - gulp

test:
  stage: test
  script:
    - npm install -g karma-cli karma-chrome-launcher karma-qunit qunit
    - karma start karma.conf.js
