image: shivjm/node-chromium-alpine:node17-chromium93

before_script:
  - npm install

build:
  stage: build
  script:
    - npm install -g gulp gulp-concat gulp-header-comment gulp-rename gulp-terser gulp-umd
    - /usr/local/bin/gulp

test:
  stage: test
  script:
    - npm install -g karma-cli karma-chrome-launcher karma-qunit qunit
    - /usr/local/bin/karma start karma.conf.js
